S02 us1 affichages legumes
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Vegglee pull request #3
Opened 2023-11-07 16:19 UTC by vinz-DY

2023-11-07 16:23 UTC, adelka69 commented
ça me parait parfait

2023-11-08 11:16 UTC, jujuck requested changes

2023-11-08 11:16 UTC, jujuck commented on frontend/src/App.jsx
> +            <div className="legumesCard">
Créer un composant LegumesCard et y associer un fichier de CSS avec sa mise en page particulière

2023-11-08 11:16 UTC, jujuck commented on frontend/src/App.jsx
> +            <div className="legumesCard">
Le premier élément du map (le composant) doit avoir une key

2023-11-08 11:16 UTC, jujuck commented on frontend/src/main.jsx
> +        .get("http://localhost:3310/api/vegetables")
Passer l'url http://localhost:3310 via la variable d'environnement import.meta.env.VITE_BACKEND_URL

2023-11-08 11:16 UTC, jujuck commented on frontend/src/App.css
> +img {
Attention, cela va concerner l'ensemble des images du site, surement des conflits futurs

2023-11-08 15:32 UTC, AntoPAA commented
ça me parait bon !

2023-11-08 15:33 UTC, AntoPAA commented
ça me parait bon !

2023-11-08 16:34 UTC, jujuck approved these changes

2023-11-08 16:35 UTC, merged