Feat display nos paniers
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Vegglee pull request #4
Opened 2023-11-14 08:35 UTC by vinz-DY

2023-11-14 08:38 UTC, vinz-DY commented
le code me semble ok 
est ce a nous de regler les conflits ou au formateur ? 
merci

2023-11-14 08:41 UTC, tessaarmelim commented
tout me semble correct, à qui de régler les conflits ?

2023-11-14 12:36 UTC, adelka69 approved these changes

2023-11-14 12:37 UTC, adelka69 commented
j'ai essayer de résoudre les conflits

2023-11-15 08:07 UTC, aimach commented
> j'ai essayer de résoudre les conflits

il faut pusher ta branche alors parce que sur la PR les conflits sont toujours présents !

2023-11-15 08:14 UTC, adelka69 approved these changes

2023-11-15 08:56 UTC, aimach requested changes

2023-11-15 08:56 UTC, aimach commented on backend/src/router.js
> +router.get("/mini_panier", (req, res) => {
Traduisez le nom de la route en anglais, ne pas mettre d'underscore (_) mais un hyphen (-)

2023-11-15 08:56 UTC, aimach commented on frontend/src/App.css
Déplacer les règles de style qui concernent la globalité de l'application dans un fichier index.css (appelé dans main.jsx)

2023-11-15 08:56 UTC, aimach commented on frontend/src/components/PanierDuo.jsx
c'est le même composant que PanierFamilial et Panier Solo, il faut factoriser le code en ne faisant qu'un seul composant et passer en props le type (duo, solo, familial) qui déterminera l'image et le h2

2023-11-15 08:56 UTC, aimach commented on frontend/src/components/PanierFamilial.jsx
c'est le même composant que PanierDuo et Panier Solo, il faut factoriser le code en ne faisant qu'un seul composant et passer en props le type (duo, solo, familial) qui déterminera l'image et le h2

2023-11-15 08:56 UTC, aimach commented on frontend/src/components/PanierSolo.jsx
c'est le même composant que PanierFamilial et Panier Duo, il faut factoriser le code en ne faisant qu'un seul composant et passer en props le type (duo, solo, familial) qui déterminera l'image et le h2

2023-11-15 08:56 UTC, aimach commented on frontend/src/pages/NosPaniersPage.jsx
> +        <PanierSolo />
cf. ce qui a été dit ci dessus, ici n'appeler qu'un seul composant où sera passé en props le type de panier

2023-11-15 08:56 UTC, aimach commented on package.json
Installer le react router dom dans le dossier frontend, il ne faut pas installer de dépendances dans la racine du projet.

2023-11-15 09:04 UTC, adelka69 commented on frontend/src/components/PanierFamilial.jsx
c'est 3 tables sql diffirentes

2023-11-15 09:48 UTC, adelka69 commented on backend/src/router.js
> +router.get("/mini_panier", (req, res) => {
fait

2023-11-15 09:50 UTC, adelka69 commented on frontend/src/App.css
fait

2023-11-15 10:18 UTC, adelka69 commented on frontend/src/components/PanierDuo.jsx
fait

2023-11-15 10:18 UTC, adelka69 commented on frontend/src/components/PanierFamilial.jsx
fait

2023-11-15 10:18 UTC, adelka69 commented on frontend/src/components/PanierSolo.jsx
fait

2023-11-15 10:21 UTC, adelka69 commented on frontend/src/pages/NosPaniersPage.jsx
> +        <PanierSolo />
fait

2023-11-15 10:23 UTC, adelka69 commented on package.json
fait

2023-11-15 11:28 UTC, aimach approved these changes

2023-11-15 11:28 UTC, merged