S02 us card detail
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Vegglee pull request #5
Opened 2023-11-14 10:25 UTC by AntoPAA

2023-11-14 10:36 UTC, adelka69 commented
good pour moi

2023-11-15 09:04 UTC, aimach requested changes

2023-11-15 09:04 UTC, aimach commented on frontend/src/components/.button.css
pourquoi il y a trois fois la même classe ?
le nom est en anglais alors que sur la PR précédente les noms de classe sont en français

2023-11-15 09:04 UTC, aimach commented on frontend/src/components/LegumeCard.css
choisir entre l'anglais et le français pour le nom des classes

2023-11-15 09:04 UTC, aimach commented on frontend/src/pages/OneVegetable.css
> +  .centered-image {
nom de classe à passer en français et camelCase

2023-11-15 09:04 UTC, aimach commented on frontend/src/pages/OneVegetable.css
> +  .imagebas {
à mettre en camelCase

2023-11-15 09:04 UTC, aimach commented on frontend/src/pages/OneVegetable.css
> +@media only screen and (max-width: 600px) {
dans les media queries, il n'est pas nécessaire de répéter le style qui s'applique déjà de manière générale.
Par exemple, pour test, on peut mettre juste : 
  .test {
    height: 20vh;
  }
car les autres propriétés sont les mêmes

2023-11-15 09:04 UTC, aimach commented on frontend/src/pages/OneVegetable.jsx
> +  if (!vegetable) {
quel est l'intérêt de cette condition ? pourquoi retourner null ?

2023-11-15 09:04 UTC, aimach commented on frontend/src/pages/OneVegetable.jsx
> +          <img src={vegetable.image} alt={vegetable.name} className="test" />
nom de className pas très parlant... que signifie "test" ?

2023-11-15 09:22 UTC, AntoPAA commented on frontend/src/components/LegumeCard.css
on choisi l'anglais

2023-11-15 11:04 UTC, aimach approved these changes

2023-11-15 13:35 UTC, vinz-DY commented
ok c'est tout bon

2023-11-15 13:36 UTC, vinz-DY approved these changes
ok pour la pr

2023-11-15 13:47 UTC, merged