S03 us recette
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Vegglee pull request #6
Opened 2023-11-15 15:26 UTC by AntoPAA

2023-11-15 15:30 UTC, vinz-DY approved these changes
tout est ok 
tout est au vert 
cool

2023-11-16 08:18 UTC, jujuck requested changes
On fait le point ensemble sur toutes les modifications

2023-11-16 08:18 UTC, jujuck commented on backend/src/router.js
> +router.get("/recettes", (req, res) => {
LE nom des autres routes est en Anglais, donc passer en receipt

2023-11-16 09:06 UTC, AntoPAA commented on backend/src/router.js
> +router.get("/recettes", (req, res) => {
j'ai garder le nom en français car c'est celle qui s'affiche quand on cherche l'URL ( a moins que je me trompe et que c'est que celle dans main)

2023-11-16 15:18 UTC, jujuck requested changes

2023-11-16 15:18 UTC, jujuck commented on frontend/src/pages/RecipePage.jsx
> +  if (recipe === null) {
A supprimer, 2 possibilités initialiser le state en [] ou utiliser le loader de la route dans main.jsx

2023-11-16 15:18 UTC, jujuck commented on backend/database/schema.sql
> +  ,image                   VARCHAR(117)
Tous mettre avec des valeurs fortes

2023-11-16 15:42 UTC, jujuck approved these changes

2023-11-16 15:43 UTC, merged