S02 us search bar
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Vegglee pull request #7
Opened 2023-11-15 15:26 UTC by vinz-DY

2023-11-15 15:29 UTC, AntoPAA approved these changes
Même la perfection n'atteint pas ce niveau de perfection

2023-11-16 15:30 UTC, jujuck requested changes

2023-11-16 15:30 UTC, jujuck commented on backend/src/router.js
> +    query = `SELECT * FROM vegetable WHERE name LIKE "%${req.query.filter}%"`;
WRONG.... Attention aux injections SQL, Va voir la DOC mysql2 requete préparée

2023-11-16 15:30 UTC, jujuck commented on backend/src/router.js
> +// Ajoutez une deuxième route pour récupérer tous les légumes sans limitation
Code mort ????

2023-11-16 15:30 UTC, jujuck commented on frontend/src/components/LegumeCard.jsx
> +// LegumeCard.jsx
Pas de code mort

2023-11-16 15:30 UTC, jujuck commented on frontend/src/components/LegumeCard.jsx
> +import axios from "axios";
Les libraires module au dessus des autres import

2023-11-16 15:30 UTC, jujuck commented on frontend/src/components/SearchBar.jsx
> +          type="text"
Il faut que tu mettes ton input avec la value de searchtext

2023-11-17 09:09 UTC, vinz-DY commented
refacto avec julien ok
en attente du ok pour voir les conflits avec branch anto validée

2023-11-17 15:38 UTC, jujuck approved these changes

2023-11-17 15:41 UTC, jujuck approved these changes

2023-11-17 15:41 UTC, merged